name: Deploy to AWS

on:
  push:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT  
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: github-action-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install -g aws-cdk

      - name: Install requried packages
        run: pip install -r requirements.txt
      
      - name: Synth stack
        run: cdk synth
      
      - name: Deploy stack
        run: cdk deploy 